# Ch. 12 예외처리

자바에서는 예외처리와 관련해 `try... catch, finally, throw` 구문을 사용한다. 

# 예외는 언제 발생하는가

예외는 크게 프로그램 작성 순간에 예측가능한 예외인 Exception, 발생할 수 있고 안할 수도 있는 Runtime Exception으로 구분할 수 있다. 

이와 관련한 클래스로 Exception과 RuntimeException이 있다. 구분과 완전히 일치하지는 않는게 Exception은 모든 예외의 부모 클래스이며 RuntimeException도 Exception을 상속받는다. 

# 예외 처리하기

다음과 같이 생긴 try, catch문을 사용해 예외를 처리한다. 

```java
try {
    ...
} catch(예외1) {
    ...
} catch(예외2) {
    ...
}
```

try 문 안에 예외가 발생할 수 있는 문장을 넣는다. 

try 문 안에서 예외가 발생하면 예외 종류에 해당하는 catch문이 수행된다. 여러 catch문에 해당되어도 가장 위에 것만 실행된다. 예외 발생 문장 뒤에 있는 문장들은 무시된다. 

try 문 안에서 예외가 발생하지 않으면 어떤 catch문도 수행되지 않는다. 

## 예시

```java
int c;
try {
    c = 4 / 0;
} catch(ArithmeticException e) {
    c = -1;  // 예외가 발생하여 이 문장이 수행된다.
}
```

## finally

예외 발생 여부와 상관없이 마지막에 반드시 실행되어야 하는 문장은 finally에 넣는다. 

# 예외 정의하고 발생시키기

```java
**class FoolException extends RuntimeException {
}**

class FoolException extends RuntimeException {
}

public class Sample {
    public void sayNick(String nick) {
        if("fool".equals(nick)) {
            **throw new FoolException();**
        }
        System.out.println("당신의 별명은 "+nick+" 입니다.");
    }

    public static void main(String[] args) {
        Sample sample = new Sample();
        sample.sayNick("fool");
        sample.sayNick("genious");
    }
}
```

# 예외 던지기(미루기)

```java
class FoolException extends Exception {
}
```

Runtime이 아닌 Exception을 정의했다. 

```java
public class Sample {
    public void sayNick(String nick) {
        try {
            if("fool".equals(nick)) {
                throw new FoolException();
            }
            System.out.println("당신의 별명은 "+nick+" 입니다.");
        }catch(FoolException e) {
            System.err.println("FoolException이 발생했습니다.");
        }
    }

    public static void main(String[] args) {
        Sample sample = new Sample();
        sample.sayNick("fool");
        sample.sayNick("genious");
    }
}
```

반드시 예외처리를 해야하기 때문에 해주었다. FoolException이 발생한 곳에서 예외처리를 하는 것이 아니라 sayNick을 호출한 곳에서 예외처리 하도록 예외처리를 던지는(미루는) 방법이 있다. 

```java
public class Sample {
    public void sayNick(String nick) throws FoolException {
        ~try {~   // try .. catch 문을 삭제할수 있다.
            if("fool".equals(nick)) {
                throw new FoolException();
            }
            System.out.println("당신의 별명은 "+nick+" 입니다.");
        }~catch(FoolException e) {
            System.err.println("FoolException이 발생했습니다.");
        }~
    }

    public static void main(String[] args) {
        Sample sample = new Sample();
        **try { // 이제 sayNick을 호출하는 main에서 예외처리 해주어야 한다**
            sample.sayNick("fool");
            sample.sayNick("genious");
        **} catch (FoolException e) {
            System.err.println("FoolException이 발생했습니다.");
        }**
    }
}
```
